package com.java.avancado.excecoes.test;

/**
 * RuntimeException:
 * Excecao que acontece no tempo de execucao do codigo
 */

public class Test02_Exception_RuntimeException {
    public static void main(String[] args) {
        /**
         * Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.toString()" because "object" is null
         */
        // Object object = null;
        // System.out.println(object.toString());

        
        /**
         * Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
         */
        // int[] vetor = {1,2};
        // System.out.println(vetor[2]);
    }
}
